---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fedora-bluebird-btx
description: This image is a fork of Fedora Silverblue for personal use by Birdie.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  - type: files
    files:
      - source: system
        # scary
        destination: /

  - type: dnf
    repos:
      copr:
      - ublue-os/packages
      files:
      - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
      nonfree: rpmfusion
    remove:
      packages:
      - firefox
      - firefox-langpacks
      - gnome-system-monitor
      - nano-default-editor
  
  - type: dnf
    install:
      packages:
      - terra-release-mesa

  - type: dnf
    replace:
    - from-repo: rpmfusion-free-updates
      allow-erasing: true
      packages:
      - old: libavcodec
        new: ffmpeg-libs
      - old: libavdevice
        new: ffmpeg-libs
      - old: libavfilter
        new: ffmpeg-libs
      - old: libavformat
        new: ffmpeg-libs
      - old: libavutil
        new: ffmpeg-libs
      - old: libheif
        new: libheif-freeworld
      - old: libswresample
        new: ffmpeg-libs
      - old: libswscale
        new: ffmpeg-libs
      - ffmpeg-libs
      - libfreeaptx
      - x264-libs
      - x265-libs
    - from-repo: updates
      allow-erasing: true
      packages:
      - libva
      - intel-gmmlib
    - from-repo: terra
      allow-erasing: true
      packages:
        - kvazaar-libs
    - from-repo: terra-mesa
      packages:
      - mesa-dri-drivers
      - mesa-filesystem
      - mesa-libEGL
      - mesa-libGL
      - mesa-libgbm
      - mesa-vulkan-drivers

  - type: script
    scripts:
    - priority.sh

  - type: dnf
    install:
      packages:
      - alacritty
      - btop
      - cmatrix
      - cargo
      - eza
      - fastfetch
      - gstreamer1-plugins-ugly
      - kf6-kirigami-addons
      - kvantum
      - mc
      - qt5ct
      - qt6ct
      - rust
      - setroubleshoot
      - signal-cli
      - starship
      - vim-default-editor
      - yazi
      - zsh
      - zsh-autocomplete
      - zsh-autosuggestions
      - zsh-html
      - zsh-syntax-highlighting

  - type: dnf
    install:
      packages:
      - ffmpeg
      - gamescope
      - libxavs
      - steam

  - type: dnf
    install:
      packages:
      - f21-backgrounds-gnome
      - f22-backgrounds-gnome
      - f23-backgrounds-gnome
      - f24-backgrounds-gnome
      - f25-backgrounds-gnome
      - f26-backgrounds-gnome
      - f27-backgrounds-gnome
      - f28-backgrounds-gnome
      - f29-backgrounds-gnome
      - f30-backgrounds-gnome

  - type: dnf
    install:
      packages:
      - f31-backgrounds-gnome
      - f32-backgrounds-gnome
      - f33-backgrounds-gnome
      - f34-backgrounds-gnome
      - f35-backgrounds-gnome
      - f36-backgrounds-gnome
      - f37-backgrounds-gnome
      - f38-backgrounds-gnome
      - f39-backgrounds-gnome
      - f40-backgrounds-gnome

  - type: dnf
    install:
      packages:
      - f41-backgrounds-gnome
      - f42-backgrounds-gnome
      - f43-backgrounds-gnome
      - bibata-cursor-theme
      - papirus-icon-theme
      - plasma-breeze
      
  - type: dnf
    install:
      packages:
      - google-arimo-fonts
      - google-droid-fonts-all
      - google-go-fonts
      - google-noto-fonts-all
      - google-noto-sans-hk-fonts
      - google-noto-serif-cjk-fonts
      - google-roboto-fonts
      - google-roboto-mono-fonts
      - google-roboto-slab-fonts
      - google-rubik-fonts

  - type: dnf
    install:
      packages:
      - arimo-nerd-fonts
      - jetbrains-mono-fonts-all
      - jetbrainsmono-nerd-fonts
      - material-icons-fonts
      - rsms-inter-fonts
      - rsms-inter-vf-fonts
      - terminus-fonts
      - terminus-fonts-console
      
  - type: dnf
    remove:
      packages:
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-background-logo
      - gnome-shell-extension-common
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list

  - type: dnf
    install:
      packages:
      - gnome-rounded-blur
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-just-perfection

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
        - com.adamcake.Bolt
        - com.brave.Browser
        - com.belmoussaoui.Decoder
        - com.belmoussaoui.Obfuscate
        - com.dec05eba.gpu_screen_recorder
        - com.discordapp.Discord
        - com.github.Matoking.protontricks
        - com.github.tchx84.Flatseal
        - com.markopejic.downloader
        - com.mattjakeman.ExtensionManager
        - com.obsproject.Studio
        - com.pokemmo.PokeMMO
        - com.protonvpn.www
        - com.rafaelmardojai.Blanket
        - com.usebottles.bottles
        - com.vixalien.sticky
        - com.vysp3r.ProtonPlus
        - dev.bragefuglseth.Keypunch
        - dev.zed.Zed
        - fr.handbrake.ghb
        - io.edcd.EDMarketConnector
        - io.gitlab.adhami3310.Converter
        - io.github.antimicrox.antimicrox
        - io.github.diegoivan.pdf_metadata_editor
        - io.github.fizzyizzy05.binary
        - io.github.idevecore.Valuta
        - io.github.Soundux
        - io.github.wartybix.Constrict
        - io.missioncenter.MissionCenter
        - md.obsidian.Obsidian
        - me.proton.Mail
        - me.proton.Pass
        - net.lutris.Lutris
        - net.runelite.RuneLite
        - org.audacityteam.Audacity
        - org.blender.Blender
        - org.desktop_plus.desktop-plus
        - org.gimp.GIMP
        - org.gnome.baobab
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Chess
        - org.gnome.clocks
        - org.gnome.Decibels
        - org.gnome.font-viewer
        - org.gnome.gitlab.YaLTeR.VideoTrimmer
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.Mahjongg
        - org.gnome.Mines
        - org.gnome.Nibbles
        - org.gnome.Papers
        - org.gnome.Polari
        - org.gnome.Showtime
        - org.gnome.SimpleScan
        - org.gnome.Snapshot
        - org.gnome.Sudoku
        - org.gnome.TextEditor
        - org.gnome.Weather
        - org.inkscape.Inkscape
        - org.kde.elisa
        - org.kde.kdenlive
        - org.kde.kid3
        - org.kde.kolourpaint
        - org.kde.kpat
        - org.kde.krename
        - org.kde.krita
        - org.kde.kstars
        - org.kde.okteta
        - org.libreoffice.LibreOffice
        - org.localsend.localsend_app
        - org.openttd.OpenTTD
        - org.pulseaudio.pavucontrol
        - org.qbittorrent.qBittorrent
        - org.remmina.Remmina
        - org.signal.Signal
        - org.virt_manager.virt-manager
        - org.videolan.VLC
        - ro.go.hmlendea.DL-Desktop
        - sh.ppy.osu

  - type: gnome-extensions
    install:
      - Alphabetical App Grid
      - Keep Favorites/Pinned Apps in AppGrid
      - Logo Menu
      - Tiling Assistant

  - type: files
    files:
      - source: applications
        # scary
        destination: /

  - type: script
    scripts:
    - post.sh

  - type: initramfs
  - type: signing
